### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by junhong7** [junhong7/Front-End-Blogs#5]
## responsive web design
- works well on any device with different display size
- easy to read and navigate without constantly zoom in or zoom out
- **interact with screen size**
### 3 main ingredients to responsive web design:
1. **Fluid grid**: all layout elements are sized in **relative unites**, such as **percentages**, instead of absolute units like **pixels**
1. **Flexible images**: sized in relative unites
1. **Media queries**: allow us to specify different CSS style rules for different browser widths

## lec 38-40:
1. new HTML elements: **header/nav/ul/li/**
1. Put text on image: make img **darker**
    use `linear-gradient(up, bottom)` to create a mask over the image
    ```CSS
    background-image: linear-gradient(rgba(0, 0, 0, 0.701), rgba(0, 0, 0, 0.31)), url(img/hero.jpg);
    ```
1. How to make image **as high as the browser viewpoint**
    set `height` property to `100vh`
    the `vh` is the the viewpoint
    ```CSS
    header {
    /* darker the image */
    background-image: -webkit-linear-gradient(rgba(0, 0, 0, 0.7), rgba(0, 0, 0, 0.7)), url(img/hero.jpg);
    background-image: linear-gradient(rgba(0, 0, 0, 0.701), rgba(0, 0, 0, 0.31)), url(img/hero.jpg);
    /* size is to control the zoom of the image*/
    background-size: cover;
    background-position: center;
    /* set image 100% of the view point(the whole page) */
    height: 100vh;
    background-attachment: fixed;
    }
    ```
1. How to make a **vertically a horizontally centered box**
    `width`,`top` and `left` set the top-left cornor of the block into the center
    `transform: translate(-50%, -50%);` to adjust the main text to the center
    ```CSS
    /* to put text in the center and above the image */
    .hero-text-box {
        position: absolute;
        width: 1140px;
        top: 50%;
        left: 50%;
        -webkit-transform: translate(-50%, -50%);
        -ms-transform: translate(-50%, -50%);
        transform: translate(-50%, -50%);
    }
    ```
1. how to design **buttons**
    `<a class="btn btn-full js--scroll-to-plans" href="#">I'm hungry</a>`
    the button is a well-designed **link**, so we use`<a></a>`to create
    ```html
    <div class="hero-text-box">
        <h1>Goodbye junk food.<br>Hello super healthy meals.</h1>
        <!-- two buttons using JS to implement -->
        <a class="btn btn-full js--scroll-to-plans" href="#">I'm hungry</a>
        <a class="btn btn-ghost js--scroll-to-start" href="#">Show me more</a>
    </div>
    ```
1. The **4 link states** in CSS: **link/visited/hover/active**
    - `a:link` - a normal, unvisited link
    - `a:visited` - a link the user has visited
    - `a:hover` - a link when the user mouses over it
    - `a:active` - a link the moment it is clicked
    > Note: **a:hover** MUST come after **a:link** and **a:visited** in the CSS definition in order to be effective.
    > Note: **a:active** MUST come after **a:hover** in the CSS definition in order to be effective.
    - The `text-decoration` property is mostly used to **remove underlines** from links
1. CSS3 transitions for **small animations**
    [CSS Transitions](https://www.w3schools.com/css/css3_transitions.asp)
    ```CSS
    /* color transition more smooth */
        -webkit-transition: background-color 0.2s, border 0.2s, color 0.2s;
        transition: background-color 0.2s, border 0.2s, color 0.2s;
    ```
    ```CSS
    /* ----- BUTTONS ----- */
    .btn:link,
    .btn:visited,
    input[type=submit] {
        display: inline-block;
        padding: 10px 30px;
        font-weight: 300;
        text-decoration: none;
        border-radius: 50px;
        /* color transition more smooth */
        -webkit-transition: background-color 0.2s, border 0.2s, color 0.2s;
        transition: background-color 0.2s, border 0.2s, color 0.2s;
    }

    .btn-full:link,
    .btn-full:visited,
    input[type=submit] {
        background-color: #e67e22;
        border: 1px solid #e67e22;
        color: #fff;
        margin-right: 20px;
    }

    .btn-ghost:link,
    .btn-ghost:visited {
        border: 1px solid #e67e22;
        color: #e67e22;
    }

    .btn:hover,
    .btn:active,
    input[type=submit]:hover,
    input[type=submit]:active {
        background-color: #cf6d17;
    }

    .btn-full:hover,
    .btn-full:active {
        border: 1px solid #cf6d17;
    }

    .btn-ghost:hover,
    .btn-ghost:active {
        border: 1px solid #cf6d17;
        color: #fff;
    }
    ```
1. How to create a simple **navigation**
    ```html
    <!-- html code -->
    <nav>
        <div class="row">
            <img src="resources/img/logo-white.png" alt="Omnifood logo" class="logo">
            <img src="resources/img/logo.png" alt="Omnifood logo" class="logo-black">
            <!-- ul is unordered list -->
            <ul class="main-nav js--main-nav">
                <!-- li is list elements -->
                <li><a href="#features">Food delivery</a></li>
                <li><a href="#works">How it works</a></li>
                <li><a href="#cities">Our cities</a></li>
                <li><a href="#plans">Sign up</a></li>
            </ul>
            <a class="mobile-nav-icon js--nav-icon"><i class="ion-navicon-round"></i></a>
        </div>
    </nav>
    ```
    ```CSS
    /* CSS code */
    /* Main navi */
    .main-nav {
        float: right;
        list-style: none;
        margin-top: 55px;
    }

    .main-nav li {
        display: inline-block;
        margin-left: 40px;
    }
    /* design the display of link */
    .main-nav li a:link,
    .main-nav li a:visited {
        padding: 10px 0;
        color: #fff;
        text-decoration: none;
        text-transform: uppercase;
        font-size: 90%;
        border-bottom: 2px solid transparent;
        -webkit-transition: border-bottom 0.2s;
        transition: border-bottom 0.2s;
    }

    .main-nav li a:hover,
    .main-nav li a:active {
        border-bottom: 2px solid #e67e22;
    }
    ```
